language: node_js
node_js: stable
addons:
  ssh_known_hosts:
  - github.com
  - coding.net
branches:
  only:
  - master
env:
  global:
    - GH_REF: github.com/oatiz/oatiz.github.io.git
    - CO_REF: git.coding.net/oatiz/oatiz.git
cache:
  yarn: true
  directories:
  - node_modules
  - themes
before_install:
- openssl aes-256-cbc -K $encrypted_a96780f20394_key -iv $encrypted_a96780f20394_iv
  -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "oatiz"
- git config --global user.email "2278966200@qq.com"
- yarn global add hexo-cli
- chmod +x .travis/deploy.sh
install:
- yarn
- if [ ! -d "themes/vexo" ]; then git clone git@github.com:oatiz/hexo-theme-vexo.git
  themes/vexo; fi
script:
- hexo clean
- hexo generate
# after_success:
after_script:
  - ".travis/deploy.sh"
  # - cd ./public
  # - git init
  # - git add .
  # - git commit -m "Site updated: `date +"%Y-%m-%d %H:%M:%S"`"
  - git push --force --quiet "https://${Travis-ci}@${GH_REF}" master:master
  - git push --force --quiet "https://${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${Travis-ci}@${GH_REF}" master:master --tags

dd:
- openssl aes-256-cbc -K $encrypted_a96780f20394_key -iv $encrypted_a96780f20394_iv
  -in travis.key.enc -out ~\/.ssh/travis.key -d
