base_url = "https://blog.oatiz.me"
title = "/home/oatiz"
description = ""
# compile_sass = true
slugify-path = true
highlight_code = true
highlight_theme = "one-dark"
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    {name = "series", rss = true},
]



theme = "mikoto"
extra_syntaxes = ["syntaxes"]


[extra]
author = "oatiz"
mikoto_title = "oatiz"
favicon = "https://github.com/GalAster/zola-theme-mikoto"
github_link = "https://github.com/GalAster/zola-theme-mikoto"

# comment `enable` to close the plugin

aplayer_enable = false
aplayer_background = false
aplayer_background_autolink = "http://music.163.com/playlist?id=4892065805"
aplayer_background_autoplay = false

live2d_enable = false

mathjax_enable = true
katex_enalbe = true
